DogWalkerAgain/DogWalkerAgain/Models/Walker.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DogWalkerAgain.Models
{
    public class Walker
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Street")]
        public string Street { get; set; }

        [Required]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required]
        [Display(Name = "State")]
        public string State { get; set; }

        [Required]
        [Display(Name = "Zip Code")]
        public string Zip { get; set; }

        [Display(Name = "Rating")]
        public int? Rating { get; set; }

        [ForeignKey("ApplicationUser")]
        public string ApplicationId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
    }
}

DogWalkerAgain/DogWalkerAgain/Controllers/HealthsController.cs
using DogWalkerAgain.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DogWalker.Controllers
{
    public class HealthsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Dogs
        public ActionResult Index()
        {
            return View();
        }

        // GET: Dogs/Details/5
        public ActionResult Details()
        {
            var userResult = User.Identity.GetUserId();
            var currentUser = db.Owners.Where(x => userResult == x.ApplicationId).FirstOrDefault();
            var currentDog = db.Dogs.Where(x => currentUser.Id == x.OwnerId).FirstOrDefault();
            var healthInfo = db.Health.Where(x => currentDog.Id == x.DogId).FirstOrDefault();
            return View(healthInfo);
        }

        // GET: Dogs/Create
        public ActionResult Create()
        {
            Health health = new Health();
            return View(health);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,HeartCondition,SeizureCondition,Allergies,Blind,Deaf,PhysicalLimitations,Comments,DogId")] Health health)
        {
            var userResult = User.Identity.GetUserId();
            var currentUser = db.Owners.Where(x => userResult == x.ApplicationId).FirstOrDefault();
            var currentDog = db.Dogs.Where(x => currentUser.Id == x.OwnerId).FirstOrDefault();
            health.DogId = currentDog.Id;
            if (ModelState.IsValid)
            {
                db.Health.Add(health);
                db.SaveChanges();
                return RedirectToAction("Create", "Demeanors");
            }

            return View(health);
        }

        // GET: Dogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            return View(dog);
        }

        // POST: Dogs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HeartCondition,SeizureCondition,Allergies,Blind,Deaf,PhysicalLimitations,Comments,DogId")] Dog dog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dog);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DogWalkerAgain/DogWalkerAgain/Controllers/WalkersController.cs
using DogWalker
    ;
using DogWalkerAgain.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DogWalker.Controllers
{
    public class WalkersController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Walkers
        public ActionResult Index()
        {
            
            var incompleteWalks = db.Walks.Where(x => x.WalkComplete == false).ToList();
            
            return View(incompleteWalks);
        }

        //Search dogs
        public ActionResult DogSearch(string dogBreed, string searchString)
        {
            var BreedList = new List<string>();

            //use LINQ to get list of dog breeds.
            IQueryable<string> BreedGet = from d in db.Dogs
                                          orderby d.Breed
                                          select d.Breed;

            BreedList.AddRange(BreedGet.Distinct());
            ViewBag.dogBreed = new SelectList(BreedList);

            var dogs = from d in db.Dogs
                       select d;


            if (!string.IsNullOrEmpty(searchString))
            {
                dogs = dogs.Where(d => d.Name.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(dogBreed))
            {
                dogs = dogs.Where(d => d.Breed == dogBreed);
            }

            return View(dogs);
        }

        //GET: Details of dog picked
        public ActionResult DogDetails(int id)
        {

            var rate = new SelectList(new[]
            {
                new { ID = "1", Name = "1" },
                new { ID = "2", Name = "2" },
                new { ID = "3", Name = "3" },
                new { ID = "3", Name = "3" },
                new { ID = "3", Name = "3" },
            },
            "ID", "Name", 1);

            ViewData["rate"] = rate;

            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            return View(dog);
        }


        // GET: Walkers/Details/5
        public ActionResult Details()
        {
            var currentPerson = User.Identity.GetUserId();
            var currentUser = db.Walkers.Where(x => x.ApplicationId == currentPerson).FirstOrDefault();
            return View(currentUser);
        }

        // GET: Walkers/Create
        public ActionResult Create()
        {
            Walker walker = new Walker();
            return View(walker);
        }

        // POST: Walkers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Street,City,State,Zip,Rating")] Walker walker)
        {
            walker.ApplicationId = User.Identity.GetUserId();
            walker.Rating = 0;
            if (ModelState.IsValid)
            {
                db.Walkers.Add(walker);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(walker);
        }

        // GET: Walkers/Edit/5
        public ActionResult Edit(int? id)
        {
            var walkerIs = db.Walkers.Where(w => w.Id == id).FirstOrDefault();
            return View(walkerIs);
        }

        // POST: Walkers/Edit/5
        [HttpPost]
        public ActionResult Edit(Walker walker)
        {
            try
            {
                db.Entry(walker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Walkers/Delete/5
        public ActionResult Delete(int id)
        {
            var walkerIs = db.Walkers.Where(w => w.Id == id).FirstOrDefault();
            return View(walkerIs);
        }

        // POST: Walkers/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var DeleteWalker = db.Walkers.Where(w => w.Id == id).FirstOrDefault();
                db.Walkers.Remove(DeleteWalker);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult WalkOpportunities()
        {
            var walkOpportunities = db.Walks.Where(x => x.WalkComplete == false && x.OwnersApprovalStatus != "approved" && x.WalkerApprovalStatus != "interested").ToList();
            return View(walkOpportunities);
        }

        public ActionResult WalkSchedule()
        {
            List<WalkDetails> myDetails = new List<WalkDetails>();

            var userResult = User.Identity.GetUserId();
            var currentWalker = db.Walkers.Where(x => userResult == x.ApplicationId).FirstOrDefault();
            var myWalks = db.Walks.Where(x => currentWalker.Id == x.WalkerId).ToList();
            foreach (Walk walk in myWalks)
            {
                var detailsOfSpecificWalk = db.WalkDetails.Where(x => walk.Id == x.WalkId && walk.OwnersApprovalStatus == "approved").SingleOrDefault();
                myDetails.Add(detailsOfSpecificWalk);
            }
            return View(myDetails);
        }

    }
}

DogWalkerAgain/DogWalkerAgain/Controllers/WalksController.cs
using DogWalkerAgain.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace DogWalkerAgain.Controllers
{
    public class WalksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Walks
        public ActionResult Index()
        {
            return View();
        }

        // GET: Walks/Details/5
        public ActionResult Details(int id)
        {
            Walk walk = db.Walks.Where(s => s.Id.Equals(id)).FirstOrDefault();
            return View(walk);
        }

        // GET: Walks/Create
        public ActionResult Create()
        {
            Walk walk = new Walk();
            return View(walk);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,WalkerApprovalStatus,OwnersApprovalStatus,WalkCompleted,OwnerId,WalkerId")] Walk walk)
        {
            var userResult = User.Identity.GetUserId();
            var currentUser = db.Owners.Where(x => userResult == x.ApplicationId).FirstOrDefault();
            walk.OwnerId = currentUser.Id;
            if (ModelState.IsValid)
            {
                db.Walks.Add(walk);
                db.SaveChanges();
                return RedirectToAction("Create", "WalkDetails");
            }

            return View(walk);
        }

        // GET: Walks/Edit/5
        public ActionResult Edit(int id)
        {
            var walk = db.Walks.Where(x => x.Id == id).FirstOrDefault();

            var appId = User.Identity.GetUserId();
            string role = db.Users.Where(x => appId == x.Id).Select(x => x.UserRole).SingleOrDefault();

            if (role == "Owner")
            {
                return View("OwnerEdit", walk);
            }

            if (role == "Walker")
            {
                return View("WalkerEdit", walk);
            }

            return View(walk);
        }

        // POST: Walks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult OwnerEdit([Bind(Include = "Id,OwnerId,WalkId,WalkerApprovalStatus,OwnersApprovalStatus,WalkComplete,WalkerId")] Walk walk)
        {
            // owner // if OwnersApprovalStatus is approved // save changes like normal // if OwnersApprovalStatus is denied // set WalkerApproval status to null && WalkerId to null // else save changes
            if (walk.OwnersApprovalStatus == "denied")
            {
                walk.WalkerApprovalStatus = null;
                walk.WalkerId = null;
            }
            if (ModelState.IsValid)
            {
                db.Entry(walk).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Owners");
            }

            return View(walk);
        }

        // POST: Walks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult WalkerEdit([Bind(Include = "Id,OwnerId,WalkId,WalkerApprovalStatus,OwnersApprovalStatus,WalkComplete,WalkerId")] Walk walk)
        {
            // walker // if WalkerApproval Status is interested // find user currently loggged in and set to WalkerId
            if (walk.WalkerApprovalStatus == "interested")
            {
                var userResult = User.Identity.GetUserId();
                var currentUser = db.Walkers.Where(x => userResult == x.ApplicationId).FirstOrDefault();
                walk.WalkerId = currentUser.Id;
            }
            if (ModelState.IsValid)
            {
                db.Entry(walk).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Walkers");
            }

            return View(walk);
        }

        // GET: Walks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Walk walk = db.Walks.Find(id);
            if (walk == null)
            {
                return HttpNotFound();
            }
            return View(walk);
        }

        // POST: Walks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Walk walk = db.Walks.Find(id);
            db.Walks.Remove(walk);
            db.SaveChanges();
            return RedirectToAction("Index", "Owners");
        }
    }
}

DogWalkerAgain/DogWalkerAgain/Views/Walkers/Create.cshtml
@{
    Layout = "~/Views/Shared/_LayoutWalker.cshtml";
}

@model DogWalkerAgain.Models.Walker

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Superhero</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DogWalkerAgain/DogWalkerAgain/Views/Walkers/Details.cshtml
@{
    Layout = "~/Views/Shared/_LayoutWalker.cshtml";
}

@model DogWalkerAgain.Models.Walker

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Owner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt>
            Rate This Walker! 
        </dt>
        <dd>
            @Html.DropDownListFor(model => model.Rating, new SelectList(new[] { 1, 2, 3, 4, 5 }, Model.Rating))
            @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Home", "Index")
</p>

DogWalkerAgain/DogWalkerAgain/Views/Walkers/DogDetails.cshtml
@{
    Layout = "~/Views/Shared/_LayoutWalker.cshtml";
}

@model DogWalkerAgain.Models.Dog

@{
    ViewBag.Title = "DogDetails";
}

<h2>DogDetails</h2>

<div>
    <h4>Dog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Owner.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Breed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Breed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpayedNeutered)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpayedNeutered)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)

        </dd>
        <dd>
            @Html.DropDownListFor(model => model.Rating, new SelectList(new[] { 1, 2, 3, 4, 5 }, Model.Rating))
            @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("View Health Info", "Details", "Healths")  |
    @Html.ActionLink("View Demeanor Info", "Details", "Demeanors")  |
    @Html.ActionLink("Back to List", "DogSearch")
</p>

DogWalkerAgain/DogWalkerAgain/Views/Walkers/DogSearch.cshtml
@{
    Layout = "~/Views/Shared/_LayoutWalker.cshtml";
}


@model IEnumerable<DogWalkerAgain.Models.Dog>

@{
    ViewBag.Title = "DogSearch";
}

<h2>DogSearch</h2>
<p>
    @Html.ActionLink("Create New", "Create")
    @using (Html.BeginForm())
    {
    <p>
        Breed: @Html.DropDownList("dogBreed", "All")
        Name: @Html.TextBox("searchString") <br />
        <input type="submit" value="Filter" />
    </p>
}
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Owner.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Breed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpayedNeutered)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Owner.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Breed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Size)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SpayedNeutered)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.ActionLink("Details", "DogDetails", new { id = item.Id })
                </td>
            </tr>
        }

    </table>

DogWalkerAgain/DogWalkerAgain/Views/Walkers/WalkOpportunities.cshtml
@{
    Layout = "~/Views/Shared/_LayoutWalker.cshtml";
}

@model IEnumerable<DogWalkerAgain.Models.Walk>

@{
    ViewBag.Title = "WalkOpportunities";
}

<h2>WalkOpportunities</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Owner.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Walker.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WalkerApprovalStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OwnersApprovalStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WalkComplete)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Owner.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Walker.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WalkerApprovalStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OwnersApprovalStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WalkComplete)
            </td>
            <td>
                @Html.ActionLink("View Walk Details", "Details", "WalkDetails", new { id = item.Id }, null)  |
                @Html.ActionLink("Request to take Walk", "Edit", "Walks", new { id = item.Id }, null)
            </td>
        </tr>
    }

</table>

DogWalkerAgain/DogWalkerAgain/Views/Walkers/WalkSchedule.cshtml
@{
    Layout = "~/Views/Shared/_LayoutWalker.cshtml";
}

@model IEnumerable<DogWalkerAgain.Models.WalkDetails>

@{
    ViewBag.Title = "WalkSchedule";
}

<h2>WalkSchedule</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Distance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfDogs)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Distance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfDogs)
            </td>
        </tr>
    }

</table>