DogWalkerAgain/DogWalkerAgain/Controllers/DogsController.cs
using DogWalkerAgain.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DogWalker.Controllers
{
    public class DogsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Dogs
        public ActionResult Index()
        {
            var userResult = User.Identity.GetUserId();
            Owner currentUser = db.Owners.Where(x => userResult == x.ApplicationId).FirstOrDefault();
            var dogList = db.Dogs.Where(x => currentUser.Id == x.OwnerId).ToList();
            return View(dogList); //pulls list of dogs owned by the owner logged in
        }

        // GET: Dogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            return View(dog);
        }

        // GET: Dogs/Create
        public ActionResult Create()
        {
            Dog dog = new Dog();
            return View(dog);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Rating,Name,Age,Breed,Size,SpayedNeutered,OwnerId")] Dog dog)
        {
            var userResult = User.Identity.GetUserId();
            var currentUser = db.Owners.Where(x => userResult == x.ApplicationId).FirstOrDefault();
            dog.OwnerId = currentUser.Id;
            dog.Rating = 0;
            if (ModelState.IsValid)
            {
                db.Dogs.Add(dog);
                db.SaveChanges();
                return RedirectToAction("Create", "Healths");
            }

            return View(dog);
        }

        // GET: Dogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            return View(dog);
        }

        // POST: Dogs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Rating,Name,Age,Breed,Size,SpayedNeutered,OwnerId")] Dog dog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dog);
        }

        // GET: Dogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            return View(dog);
        }

        // POST: Dogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dog dog = db.Dogs.Find(id);
            db.Dogs.Remove(dog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DogWalkerAgain/DogWalkerAgain/Controllers/WalksController.cs
using DogWalkerAgain.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace DogWalkerAgain.Controllers
{
    public class WalksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Walks
        public ActionResult Index()
        {
            return View();
        }

        // GET: Walks/Details/5
        public ActionResult Details(int id)
        {
            Walk walk = db.Walks.Where(s => s.Id.Equals(id)).FirstOrDefault();
            return View(walk);
        }

        // GET: Walks/Create
        public ActionResult Create()
        {
            Walk walk = new Walk();
            return View(walk);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,WalkerApprovalStatus,OwnersApprovalStatus,WalkCompleted,OwnerId,WalkerId")] Walk walk)
        {
            var userResult = User.Identity.GetUserId();
            var currentUser = db.Owners.Where(x => userResult == x.ApplicationId).FirstOrDefault();
            walk.OwnerId = currentUser.Id;
            if (ModelState.IsValid)
            {
                db.Walks.Add(walk);
                db.SaveChanges();
                return RedirectToAction("Create", "WalkDetails");
            }

            return View(walk);
        }

        // GET: Walks/Edit/5
        public ActionResult Edit(int id)
        {
            var walk = db.Walks.Where(x => x.Id == id).FirstOrDefault();

            var appId = User.Identity.GetUserId();
            string role = db.Users.Where(x => appId == x.Id).Select(x => x.UserRole).SingleOrDefault();

            if (role == "Owner")
            {
                return View("OwnerEdit", walk);
            }

            if (role == "Walker")
            {
                return View("WalkerEdit", walk);
            }

            return View(walk);
        }

        // POST: Walks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult OwnerEdit([Bind(Include = "Id,OwnerId,WalkId,WalkerApprovalStatus,OwnersApprovalStatus,WalkComplete,WalkerId")] Walk walk)
        {
            // owner // if OwnersApprovalStatus is approved // save changes like normal // if OwnersApprovalStatus is denied // set WalkerApproval status to null && WalkerId to null // else save changes
            if (walk.OwnersApprovalStatus == "denied")
            {
                walk.WalkerApprovalStatus = null;
                walk.WalkerId = null;
            }
            if (ModelState.IsValid)
            {
                db.Entry(walk).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Owners");
            }

            return View(walk);
        }

        // POST: Walks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult WalkerEdit([Bind(Include = "Id,OwnerId,WalkId,WalkerApprovalStatus,OwnersApprovalStatus,WalkComplete,WalkerId")] Walk walk)
        {
            // walker // if WalkerApproval Status is interested // find user currently loggged in and set to WalkerId
            if (walk.WalkerApprovalStatus == "interested")
            {
                var userResult = User.Identity.GetUserId();
                var currentUser = db.Walkers.Where(x => userResult == x.ApplicationId).FirstOrDefault();
                walk.WalkerId = currentUser.Id;
            }
            if (ModelState.IsValid)
            {
                db.Entry(walk).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Walkers");
            }

            return View(walk);
        }

        // GET: Walks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Walk walk = db.Walks.Find(id);
            if (walk == null)
            {
                return HttpNotFound();
            }
            return View(walk);
        }

        // POST: Walks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Walk walk = db.Walks.Find(id);
            db.Walks.Remove(walk);
            db.SaveChanges();
            return RedirectToAction("Index", "Owners");
        }
    }
}

DogWalkerAgain/DogWalkerAgain/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dog Walker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dog Walker</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DogWalkerAgain/DogWalkerAgain/Views/Shared/_LayoutOwner.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Owners", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("My Profile", "Details", "Owners")</li>
                    <li>@Html.ActionLink("My Dogs", "Index", "Dogs")</li>
                    <li>@Html.ActionLink("Find Walkers", "WalkerSearch", "Owners")</li>
                    <li>@Html.ActionLink("Request Walk", "Create", "Walks")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DogWalkerAgain/DogWalkerAgain/Views/Shared/_LayoutWalker.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Find Dogs To Walk", "DogSearch", "Walkers")</li>
                    <li>@Html.ActionLink("My Profile", "Details", "Walkers")</li>
                    <li>@Html.ActionLink("Opportunities", "WalkOpportunities", "Walkers")</li>
                    <li>@Html.ActionLink("My Walks", "WalkSchedule", "Walkers")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>